### ISSUE TITLE
有可能通过docker一键部署么

### ISSUE THREAD

**Issue by kokojacket** [v5star/rustdesk-api#4]
有可能通过docker一键部署么

**Comment by v5star** [comment]
计划中一键部署脚本的编写，docker的话，还在学习中，你有好的一键脚本或思路也可以分享一下

**Comment by kokojacket** [comment]
哈，我是个小白中的小白~大佬加油

**Comment by kokojacket** [comment]
找到项目了：https://github.com/kingmo888/rustdesk-api-server
另外我打包了一个镜像到dockerhub：kokojack/rustdesk-api-server:latest
rustdesk全套（账户管理api+中继服务器）-docker-compose
````
version: '3'

networks:
  rustdesk-net:
    name: rustdesk-net
    ipam:
      driver: default
      config:
        - subnet: 172.12.0.0/16
          gateway: 172.12.0.1

services:
  #账户API，项目地址:https://github.com/kingmo888/rustdesk-api-server
  rustdesk-api-server:
    container_name: rustdesk-api-server
    image: kokojack/rustdesk-api-server:latest
    environment:
      - HOST=0.0.0.0
      - TZ=Asia/Shanghai
      - CSRF_TRUSTED_ORIGINS=<域名>:<端口> #api填写地址
    volumes:
      - /share/docker/rustdesk-api-server-main/db.sqlite3:/rustdesk-api-server/db.sqlite3
     #注意，需要提前建立文件夹放入db.sqlite3文件，下载直连：blob:https://github.com/f7f71567-3821-48d7-bd31-9d9429ac2859
     # - /etc/timezone:/etc/timezone:ro
     # 威联通的/etc/timezone时间文件夹有问题。所以我直接给注释掉了
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "21114:21114"
    networks:
      - rustdesk-net
  
  #中继服务器
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116 # 自定义 hbbs 映射端口
      - 21116:21116/udp # 自定义 hbbs 映射端口
    image: rustdesk/rustdesk-server
    command: hbbs -r <域名>:21117 # 填入个人域名或 IP + hbbr 映射端口
    volumes:
      - /share/docker/rustdesk/hbbs:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117 # 自定义 hbbr 映射端口
    image: rustdesk/rustdesk-server
    command: hbbr
    volumes:
      - /share/docker/rustdesk/hbbr:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
````
目前有个问题是，搭建的web网页客户端无法连接api服务器，不知道为啥。。
